basic:
  seed: 42
  n_envs: 24
  n_steps: 360
  step_count: 100000000 # 100M
  pretrained_path: models/rl_model_10000000_model.zip

resume:
  is_resume: True
  run_id: faithful-thunder-392  # run id in wandb
  resume_num_timesteps: 100000000

callbacks:  
  eval:
    best_model_save_path: './models/'
    # log_path: './models/'
    eval_freq: 3600  # Run it every 10 training iterations
    n_eval_episodes: 3  # Run 5 games
    deterministic: False
    render: False

  checkpoints:
    save_freq: 50000  # 1,200,000
    save_path: './models/'
    name_prefix: 'rl_model'
    verbose: 0

model:
    model_update_step_freq: 50000
    model_arche: "mlp"  # "cnn" or "mlp"
    params:
      verbose: 0
      tensorboard_log: "./tensorboard/"
      learning_rate: 0.001
      gamma: 0.998
      gae_lambda: 0.95
      batch_size: 1024
      n_steps: 1024