basic:
  seed: 42
  n_envs: 24
  n_steps: 360
  step_count: 100000000 # 100M
  pretrained_path: models/rl_cnn_model_38400000_steps.zip
  debug: False

resume:
  is_resume: True
  run_id: glowing-rocket-437_v2  # run id in wandb
  resume_num_timesteps: 38400000

callbacks:  
  eval:
    best_model_save_path: './models/'
    eval_freq: 3600  
    n_eval_episodes: 3  # Run 3 games
    deterministic: False
    render: False

  checkpoints:
    save_freq: 50000  # 1,200,000
    save_path: './models/'
    name_prefix: rl_cnn_model
    verbose: 0

model:
    model_update_step_freq: 50000
    n_stack: 4
    params:
      verbose: 0
      tensorboard_log: "./tensorboard/"
      learning_rate: 0.001
      gamma: 0.998
      gae_lambda: 0.95
      batch_size: 2048
      n_steps: 1024  # 元のモデルからは変更できない