basic:
  seed: 42
  run_id: stack4_ep10_customnn_v3  # faithful-thunder-392  # run id in wandb
  debug: False
  method: BC
  batch_size: 2048
  n_stack: 4
  n_envs: 1
  features_dim: 128

trajectory:
  episode_dir: ../../input/lux_ai_toad1800_episodes_1108/
  data_dir: ./tmp_data/
  only_win: False
  only_one_sub: True

BC:
  trainer_params:
    n_epochs: 1
    log_interval: 100
    reset_tensorboard: True