basic:
  seed: 42
  n_envs: 16
  step_count: 500000000 # 500M
  pretrained_il_path: ./models/best.pth
  pretrained_rl_path: None  # ./models/latest.zip
  debug: False

resume:
  is_resume: True
  run_id: rl_simple_model_action6_v4  # upbeat-vortex-784  # run id in wandb
  resume_num_timesteps: 0 # 27600000

callbacks:  
  eval:
    n_envs: 5
    params:
      eval_freq: 10  # when rollout start
      n_eval_episodes: 5 # Run 4 games
      deterministic: False
      render: False

  checkpoints:
    save_freq: 100000
    save_path: 'models/'
    name_prefix: rl_cnn_model
    verbose: 0

model:
    model_update_step_freq: 100000
    params:
      verbose: 0
      tensorboard_log: "./tensorboard/"
      learning_rate: 0.00001
      batch_size: 128
      n_steps: 12288 # 8192 # 2048
      gamma: 0.998
      gae_lambda: 0.95
      ent_coef: 0.01
      clip_range: 0.1
      target_kl: 0.003  # 方策の更新を大きく行わないためにKL-targetを小さくする
      # clip_range_vf: 0.3