basic:
  seed: 42
  n_envs: 12
  n_steps: 360
  step_count: 500000
  resume: False
  pretrained_path: None

callbacks:  
  eval:
    best_model_save_path: './logs/'
    log_path: './logs/'
    eval_freq: 720  # Run it every 2 training iterations
    n_eval_episodes: 30  # Run 30 games
    deterministic: False
    render: False

  checkpoints:
    save_freq: 100000
    save_path: './models/'
    name_prefix: 'model'
    replay_num_episodes: 5

model:
    verbose: 0
    tensorboard_log: "./tensorboard/"
    learning_rate: 0.001
    gamma: 0.998
    gae_lambda: 0.95
    batch_size: 1024
    n_steps: 1024