basic:
  seed: 42
  n_envs: 1
  run_id: faithful-thunder-392  # run id in wandb
  debug: True
  step_count: 1000000 # 1M
  method: BC   # GAIL  # BC
  trajectory_dir: "./trajectory/"

callbacks:  

  checkpoints:
    save_freq: 50000  # 1,200,000
    save_path: './models/'
    name_prefix: 'rl_model'
    verbose: 0

model:
    model_arche: "cnn"  # "cnn" or "mlp"
    batch_size: 1024
    params:
      verbose: 1
      tensorboard_log: "./tensorboard/"
      learning_rate: 0.001
      gamma: 0.998
      gae_lambda: 0.95
      batch_size: 1024
      n_steps: 1024