basic:
  seed: 42
  run_id: None  # faithful-thunder-392  # run id in wandb
  debug: False
  method: BC
  batch_size: 64
  episode_dir: ../../input/lux_ai_toad1800_episodes_1108/
  data_dir: ./tmp_data/

BC:
  trainer_params:
    n_epochs: 1
    log_interval: 10000
    reset_tensorboard: True